# services/checkout/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  selector:
    app: checkout
  ports:
    - name: http
      port: 8080
      targetPort: http
