# services/accounts/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  ports:
    - name: http
      port: 8080
      targetPort: http
