# services/payments/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  selector:
    app: payments
  ports:
    - name: http
      port: 8080
      targetPort: http
